version: '2'
services:
    tuto2-app:
        image: tuto2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tuto2-mysql:3306/tuto2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tuto2-elasticsearch:9300
        ports:
            - 8080:8080
    tuto2-mysql:
        extends:
            file: mysql.yml
            service: tuto2-mysql
    tuto2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tuto2-elasticsearch
