version: '2'
services:
    tutorial1-app:
        image: tutorial1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tutorial1-mysql:3306/tutorial1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tutorial1-elasticsearch:9300
        ports:
            - 8080:8080
    tutorial1-mysql:
        extends:
            file: mysql.yml
            service: tutorial1-mysql
    tutorial1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tutorial1-elasticsearch
